<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon></ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ScottPlot.WPF" Version="5.0.55" />
  </ItemGroup>
</Project>
